version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: game123/reverseproxy
  backend_user:
    build:
      context: ../../udagram-user
    image: game123/udagram-user
  backend_feed:
    build:
      context: ../../udagram-feed
    image: game123/udagram-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: game123/udagram-frontend
